#!/bin/bash

if ! test -e src/c-utils/prepare ; then
   echo "Can't find c-utils source. Did you remember to checkout the"
   echo "submodule? (git submodule init && git submodule update)"
   exit 2
fi

echo "preparing src/c-utils:"
cd src/c-utils
./prepare
if [[ $? != 0 ]] ; then
    exit $rc
fi
cd -

if aclocal --force -I ./maint/config && autoheader -f && autoconf -f; then
	echo "configure script successfully regenerated"
        exit 0
else
	echo "some part of configure regeneration failed"
        exit 1
fi
