src_libaesop_a_SOURCES += \
 src/components/aebdb.ae \
 src/components/aefile.ae \
 src/components/resourcebuilder.ae \
 src/components/aesocket.ae \
 src/components/timer.ae 

AE_SRC += \
 src/components/aebdb.ae \
 src/components/aefile.ae \
 src/components/resourcebuilder.ae \
 src/components/aesocket.ae \
 src/components/timer.ae 
