#!/bin/sh

# NOTE: This script is deprecated.  Use setup-hs-local instead.

echo "This script is deprecated.  Use setup-hs-local instead."
exit 1
sudo apt-get install ghc6 haskell-utils happy alex libghc6-mtl-dev
