#!/bin/bash

cmdpath=$(echo $0|sed -e "s|^\(.*\)/[^/]*$|\1|")

VERSION=0.4.2

pushd ${cmdpath}
wget --connect-timeout=2 --read-timeout=2 --tries=1 http://hackage.haskell.org/packages/archive/language-c/${VERSION}/language-c-${VERSION}.tar.gz
popd

set -x

# put happy and alex in the path
PATH=$HOME/.cabal/bin:$PATH

# use local copy for now
tar xvfz ${cmdpath}/language-c-${VERSION}.tar.gz >/dev/null 2>&1 
if [ $? != 0 ]; then
        echo "Untar of language-c-${VERSION}.tar.gz failed!"
        exit 1
fi

echo "Patching language-c-${VERSION} with Aesop extensions..."

cd language-c-${VERSION}
patch -p 1 < ${OLDPWD}/${cmdpath}/language-c-${VERSION}.patch >/dev/null 2>&1
if [ $? != 0 ]; then
        echo "Patch of language-c failed!"
        exit 1
fi

echo "Building/Installing language-aesop-${VERSION} package..."
cabal configure
cabal build
cabal install

cd -
# rm -r language-c-${VERSION}
