#!/bin/bash

# SETUP-AESOP
# Downloads language-c
# Patches it with Aesop modifications, making package language-aesop
# Installs it with cabal

# broken for ./setup-aesop
#MAINT_HS=$(echo $0|sed -e "s|^\(.*\)/[^/]*$|\1|")

pushd $(dirname $0)
MAINT_HS=$PWD
popd

echo ${MAINT_HS}

VERSION=0.4.2

pushd ${MAINT_HS}
wget -c --connect-timeout=2 --read-timeout=2 --tries=1 http://hackage.haskell.org/packages/archive/language-c/${VERSION}/language-c-${VERSION}.tar.gz
popd

# Put happy and alex in the path
PATH=$HOME/.cabal/bin:$PATH

tar xfz ${MAINT_HS}/language-c-${VERSION}.tar.gz >/dev/null
if [[ $? != 0 ]]
then
    echo "Untar of language-c-${VERSION}.tar.gz failed!"
    exit 1
fi

echo "Patching language-c-${VERSION} with Aesop extensions..."

cd language-c-${VERSION}
patch -p 1 < ${MAINT_HS}/language-c-${VERSION}.patch > /dev/null
if [[ $? != 0 ]]
then
    echo "Patch of language-c failed!"
    exit 1
fi

echo "Building language-aesop-${VERSION} package..."
cabal configure
cabal build
echo "Installing language-aesop-${VERSION} package..."
cabal install

# rm -r language-c-${VERSION}

# Local Variables:
# sh-basic-offset: 4
# End:
