#!/bin/sh

OLDPWD=$PWD

cmdpath=$(echo $0|sed -e "s|^\(.*\)/[^/]*$|\1|")

verbose=

while [ x"$1" != x ]; do
        case $1 in
                -v) verbose=1
                    shift
                    continue;;
                *) arg=shift
                   echo "unknown argument $arg"
                   exit 1
        esac
done

install_pkg()
{
    pname=$1
    version=$2
    cd ${OLDPWD}
    wget http://hackage.haskell.org/packages/archive/$pname/$version/$pname-$version.tar.gz 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo "Get of $pname-$version from hackage.haskell.org failed!" >&2
        exit 1
    fi
    tar xvfz $pname-$version.tar.gz 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo "Untar of $pname-$version.tar.gz failed!" >&2
        exit 1
    fi
    cd $pname-$version
    runhaskell Setup configure --prefix=${OLDPWD}/GHC --user 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo "configure of $pname-$version failed!" >&2
        exit 1
    fi
    runhaskell Setup build 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo "build of $pname-$version failed!" >&2
        exit 1
    fi
    runhaskell Setup install --user 2>&1 >/dev/null
    if [ $? != 0 ]; then
        echo "install of $pname-$version failed!" >&2
        exit 1
    fi
}

vpkg()
{
    if [ "x$verbose" != "x" ]; then
        install_pkg $1 $2 
    else
        echo -n "Installing package $1, version $2..."
        install_pkg $1 $2 > /dev/null
        echo "done."
    fi
}
       
vpkg transformers 0.2.2.0
vpkg mtl 2.0.1.0
vpkg happy 1.18.6
vpkg alex 2.3.5
vpkg regex-base 0.93.2
vpkg regex-posix 0.94.4
vpkg regex-pcre-builtin 0.94.2.1.7.7
vpkg syb 0.3
