
# Sources that need to be compiled in to stdlib
stdlibsources =

# headers that need to be installed for stdlib
stdlibheaders =

# Extra flags (mainly for built sources)
stdlibcppflags =

include src/std/resources/Makefile.subdir

lib_LTLIBRARIES += lib/libaesop-std.la
lib_libaesop_std_la_SOURCES = $(stdlibsources)

stdlibdir = $(includedir)/aesop/std

stdlib_HEADERS = $(stdlibheaders)

